- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: SELINUX=disabled
#- name: reboot system
#  reboot:
  
- name: edit host file
  lineinfile:
    path: /etc/hosts
    line: '{{item}}'
  loop:
    - "192.168.75.37 stgMongodb37"
    - "192.168.75.38 stgMongodb38"
    - "192.168.75.39 stgMongodb39"
- name: change python to python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
- name: install pymongo
  pip:
    name: pymongo
- name: change python to python2
  file:
    src: /usr/bin/python2 
    dest: /usr/bin/python
    state: link