---
- name: restart enp0s3
  shell: >
    dhclient -r enp0s3 && dhclient enp0s3
  tags: enp
- name: remove old package
  yum:
    name: elasticsearch
    state: absent
- name: remove old config
  file:
    path: '{{item}}'
    state: absent
  loop:
    - /etc/elasticsearch
    - /usr/lib/systemd/system/elasticsearch*
- name: edit sysconfig
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    regexp: '^ES_JAVA_OPTS'
    line: 'ES_JAVA_OPTS="-Xms512m -Xmx512m"'
    state: absent
    #backrefs: yes
- name: edit sysconfig
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    regexp: '^MAX_LOCKED_MEMORY'
    line: 'MAX_LOCKED_MEMORY=unlimited'
    state: absent
    #backrefs: yes  
  tags: edit

- name: 'edit limit: soft'
  lineinfile: 
    path: /etc/security/limits.conf
    regexp: "^elasticsearch soft"
    line:  "elasticsearch soft memlock unlimited"
    #backrefs: yes
    state: present
- name: 'edit limit: hard'
  lineinfile: 
    path: /etc/security/limits.conf
    regexp: "^elasticsearch hard"
    line:  "elasticsearch hard memlock unlimited"
    #backrefs: yes
    state: present
    
   
- name: edit systemd
  lineinfile: 
    path: /usr/lib/systemd/system/elasticsearch.service
    line: 'LimitMEMLOCK=infinity'
    insertbefore: '^LimitFSIZE'
    state: present
  tags: edit_limit
  ignore_errors: yes
